환경설정 구현
wafflestudio/SNUTT-iOS pull request #100
Opened 2022-08-21 19:25 UTC by peng-u-0807

- 환경설정 쪽 메뉴 세팅+로컬 아이디 추가 Scene UI 정도 구현했습니다
- `WIP`인 부분은 후속 작업에서 이어서 진행할 예정입니다

2022-08-23 06:45 UTC, shp7724 reviewed
수고하셨습니다~ 
아직 Draft긴 한데 리뷰 남겼어요

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/User.swift
> +}
사소한거긴 한데 기존에는 `data` 대신 `dto`라는 변수명을 썼었어요.

```suggestion
extension User {
    init(from dto: UserDto) {
        localId = dto.local_id
        fbName = dto.fb_name
        email = dto.email
    }
}
```

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Menu.swift
> +    var title: String
`MenuSheet` 또는 [SwiftUI Menu](https://developer.apple.com/documentation/swiftui/menu)와 혼동의 여지가 있는 이름인 것 같아서 다른 걸로 바꾸면 좋을 것 같아요. 예를들면 `SettingsListItem`??

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift
> +    let viewModel: SettingViewModel
파일의 실제 경로와 프로젝트상 경로가 다른 것 같아요.

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Menu.swift
> +        case .addLocalId: return "아이디 비번 추가"
원래 SNUTT에서도 이랬던거같긴 한데 표준어로 바꾸는게 좋을 것 같아요.

```suggestion
        case .addLocalId: return "아이디 / 비밀번호 추가"
```

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/Settings/AccountSettingScene.swift
> +    }
SettingScene의 하위 메뉴들은 전부 Stateless하게 만들 수 있지 않을까요?
menuList도 다른곳에서 구독해서 받아오는게 아니라 initializer를 통해 주입받도록 하는게 data flow를 파악하기에 훨씬 편할 것 같다는 생각입니다.

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/SettingsService.swift
> +    }
이 코드는 AccountSetting View (또는 ViewModel) 쪽으로 옮겨도 될 것 같아요. Service는 repository를 호출하거나 global state를 **변경하는** action들만 정의해놓고 있어서요.

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/SettingsService.swift
> +    }
UserDefaults에 저장된 유저 정보를 가져오는 것은 앱이 맨 처음 시작될 때 딱 한번만 필요하지 않나요?
유저 정보 불러오는 건 UserService에서 처리하도록 하고, `accountMenuList`를 만들 때 `userLocalId` 같은 게 필요해진다면 `appState.user`에서 가져와서 사용하면 될 것 같습니다.

2022-08-23 06:45 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/Settings/DeveloperInfoScene.swift
> +}
`Scene`은 전역 상태를 갖고 있는 View를 가리킬 때 사용하고 있어서, 이 경우에는 `DeveloperInfoView`라고 하는게 더 적절하지 않을까 하는 생각입니다. (Stateless 하다는 것을 명확히 전달하기 위해)

2022-08-23 07:34 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Scenes/Settings/AccountSettingScene.swift
> +    }
@shp7724 환경설정>계정설정 화면은 유저 로컬 아이디 추가 여부나 페북 연동 여부에 따라 메뉴가 실시간으로 변해야 하므로 AppState를 구독이 불가피하다고 생각했습니다.

2022-08-23 07:42 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Services/ValidationService.swift
> +}
@shp7724 valid하지 않은 입력에 대해서는 alert를 띄워야 하므로 AppState에 대한 접근이 필요할 것이라 판단하여 Service로 분류해둔 상태입니다. alert 관련 작업 추가되고 난 뒤에 구현하려고 했던 부분이라서 WIP인데 신홍님 다른 브랜치에서 alert 관련 로직을 GlobalUIService 이쪽에 넣어두셨으니 Validation 로직은 따로 분리해도 될 것 같네요. 추후 작업할때 참고할게요

2022-08-23 07:44 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Menu.swift
> +    var title: String
@shp7724 그렇네요 이건 수정할게요

2022-08-23 07:48 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Services/SettingsService.swift
> +    }
@shp7724 안그래도 이 부분 발견해서 Draft 전환했습니다 PR 재오픈 전에 수정 예정입니다

2022-08-23 08:00 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Services/SettingsService.swift
> +    }
아래의 [여기](https://github.com/wafflestudio/SNUTT-iOS/pull/100#discussion_r952266200)와 묶이는 내용이라서 한번에 수정될 것 같네요

2022-08-30 08:45 UTC, shp7724 commented
이거 계속 작업중이신건가요?

2022-08-30 11:18 UTC, peng-u-0807 commented
@shp7724 네 이전에 리뷰 남겨주신 부분에서 수정할 것도 있고 해서 Draft로 남겨두었는데 중간에 웹뷰 구현하고+최근에 다른 일이 많아서 진행을 못하고 있었어요. 조만간 마무리하고 PR 재오픈할게요

2022-09-07 17:04 UTC, peng-u-0807 commented
GlobalUIService랑 엮일 부분이 많아서 더이상 작성하는건 조금 무의미할 것 같아 머지 후 새로 브랜치 파서 마무리하려 하는데 괜찮을까요? 큼직한 수정사항은 반영하였습니다. @shp7724

2022-09-08 02:52 UTC, shp7724 commented
@peng-u-0807 현재 master로부터 pull 한번 해주는것만으로는 충분하지 않은 상황인건가요?

2022-09-08 04:11 UTC, peng-u-0807 commented
@shp7724 master와 clean-arch 모두 필요하다보니 두번 리베이스 과정에서 PR이 무거워질 것 같아 한번 끊을까 싶었는데, 그냥 여기서 계속 이어서 할까요? 어느쪽이든 크게 상관은 없습니다

2022-09-08 04:56 UTC, shp7724 commented
@peng-u-0807 음..그러면
- #105 브랜치가 리뷰가 어느정도 되었기도 했고 후속 PR에서 계속 필요한 상황이니 먼저 approve 주시면 master에 머지할게요.
- 그 이후 이 브랜치를 master 위에 rebase하고 컨플릭트 수정하고 force-push하시면 PR이 무거워질 일은 없을 것 같아요.
아직 개발진행중인 브랜치를 머지하면 나중에 버그 어디서 난건지 트래킹하기 어려울것 같아서요, 이렇게 해주시면 좋을 것 같습니다!
-

2022-09-17 06:44 UTC, JSKeum requested changes

2022-09-17 06:44 UTC, JSKeum commented on SNUTT-2022/SNUTT/ViewModels/AccountSettingViewModel.swift
> +    }
viewmodel에서는 View를 제외한 데이터만 다루면 좋겠어요!

2022-09-19 03:32 UTC, peng-u-0807 commented
@JSKeum @shp7724 일단 rebase 후 환경 설정 메뉴 관련 코드를 Scene으로 이동하는 수정사항 정도 반영해두었습니다. 아직 구현되지 않은 부분들은 브랜치 잘게 파서 작업하겠습니다. master보다 너무 뒤에 있다보니 만일 새롭게 merge할 PR이 있다면 가급적 이 PR 뒤로 부탁드립니다...

2022-09-19 05:23 UTC, shp7724 approved these changes
넵 이건 일단 머지하기로 했었죠? Approve 해두겠습니다~!

2022-09-19 05:25 UTC, shp7724 commented on SNUTT-2022/SNUTT/ViewModels/AccountSettingViewModel.swift
> +    }
@JSKeum 머지할 수 있게 approve 부탁드려요

2022-09-19 08:15 UTC, merged