Notification 구현
wafflestudio/SNUTT-iOS pull request #110
Opened 2022-09-02 14:31 UTC by shp7724

- 노티 기능을 구현했습니다.
- 아이콘에 빨간 점은 #109 머지된 이후에 구현하겠습니다.

<img width="564" alt="스크린샷 2022-09-02 오후 11 31 20" src="https://user-images.githubusercontent.com/33917774/188171864-d14bb6e5-a67d-4b93-a926-044779065b29.png">

2022-09-25 04:34 UTC, peng-u-0807 reviewed
리뷰 남깁니다~

2022-09-25 04:34 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Repositories/Router/NotificationRouter.swift
> +    var baseURL: URL { return URL(string: "https://snutt-api-dev.wafflestudio.com" + "/notification")! }
baseURL은 직접적으로 써주기보단 `NetworkConfiguration.serverBaseURL`로 불러오면 될 것 같아요

2022-09-25 04:34 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Services/NotificationService.swift
> +    private func _fetchNotifications(updateLastRead: Bool = false) async throws {
여기 `updateLastRead = false`로 설정하신 이유가 따로 있나요? 어차피 어떤 값을 올리든 값을 올리는 이상 서버에서는 마지막 Read 시점을 저장하도록 되어있어서([API docs](https://github.com/wafflestudio/snutt/wiki/API-Notification)) 아래의 `fetchinitialNotifications` 함수같은 경우도 따로 인자 받지 않고 true로 디폴트 해도 될거같아요
빨간 점 노티는 구현하지 않은 PR이라 좀 앞선 얘기겠지만 디버깅이나 UI Test같은 특수 상황을 위해 `updateLastRead = true`일 때는 `explicit`에 값을 넘기고, `updateLastRead = false`일 때는 `explicit`을 전달하지 않는 방법도 있을 것 같네요.

2022-09-25 04:35 UTC, peng-u-0807 commented
그러고보니 https://github.com/wafflestudio/SNUTT-iOS/pull/109는 머지 완료되었는데 혹시 아직 작업중인 PR일까요?

2022-09-25 05:36 UTC, shp7724 commented
@peng-u-0807 아하 머지된걸 잊고있었네요
마저 작업해볼게요

2022-09-25 05:52 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/NotificationService.swift
> +    private func _fetchNotifications(updateLastRead: Bool = false) async throws {
메인 타임테이블 화면에 진입했을때 우선적으로 noti api를 미리 호출합니다. (이유는 노티 화면에 진입했을 때 추가적으로 로딩을 하지 않기 위해.. 일종의 prefetching입니다)

그리고 노티화면에 진입하면 한번 더 api를 날려서 새로고침 해주고, 이때 unreadCount를 갱신합니다.

그래서 별도의 인자를 둔거였는데, explicit에 False를 넣어도 set으로 처리한다는 건가요? 한번 테스트가 필요하겠네요

2022-09-27 09:44 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/NotificationService.swift
> +    private func _fetchNotifications(updateLastRead: Bool = false) async throws {
@peng-u-0807 

[서버 코드](https://github.com/wafflestudio/snutt/blob/35a76d8f110be27f2c0b74dee59bcbfd28d6a173/src/api/routes/NotificationRouter.ts#L21)를 보니 값을 업데이트하려면 `explicit`에 [truthy value](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)가 들어가야 하네요. `값에 관계 없이 set 되면`이라는 말도 같은 맥락인것같습니다.

2022-09-28 04:57 UTC, peng-u-0807 requested changes
빨간 점 노티가 알림 확인 후에도 사라지지 않는 문제가 있습니다~ 

https://user-images.githubusercontent.com/70614553/192690745-e5015157-82f7-4061-93b2-da13e731a5b7.mp4

2022-09-28 05:00 UTC, peng-u-0807 commented
그리고 이건 어느 브랜치에서 수정된 부분인진 모르겠는데 휴지통 아이콘 파일이 이전과 달라졌네요(이미지 크기가 커짐) 확인 부탁드립니다

![image](https://user-images.githubusercontent.com/70614553/192691289-a57074d6-c7b1-4ffe-ac03-60a84b94da47.png)

2022-09-28 05:33 UTC, shp7724 commented
@peng-u-0807 

> 빨간 점 노티가 알림 확인 후에도 사라지지 않는 문제가 있습니다~

이미 구현된 줄 알았던 로직이 미완이었네요 수정했습니다!
unreadCount를 제가 되돌릴수가 없어서 테스트해보기가 어려운데, 되는지 한번만 봐주시면 감사하겠습니다.

> 휴지통 아이콘 파일이 이전과 달라졌네요

아마 이번 PR에서 수정된 게 맞을거에요. 한달전이라 정확한 이유는 잘 기억이 안나지만 해당 휴지통 아이콘이 알림 View와 Sheet에서 둘다 사용되는데, 다른 아이콘들과 margin이 통일이 안됐던 문제가 있던것같아요. (피그마 전반적으로 그런 문제가 있음)

다크모드용 아이콘도 새로 뽑아야돼서 겸사겸사 noti icon set 전부 새로 뽑았던 것 같습니다.

2022-09-28 06:35 UTC, peng-u-0807 commented
@shp7724 이전에 말씀드렸던 `NotificationRouter`에서 BaseURL 수정사항 반영 부탁드립니다! 그리고 알림은...저도 확인을 해버려서 테스트가 어렵네요 다른 방법을 써야될 것 같습니다

2022-09-28 07:33 UTC, shp7724 commented on SNUTT-2022/SNUTT/Repositories/Router/NotificationRouter.swift
> +    var baseURL: URL { return URL(string: "https://snutt-api-dev.wafflestudio.com" + "/notification")! }
반영했습니다!

2022-09-28 07:56 UTC, shp7724 commented
@peng-u-0807 아마 잘 작동 할거에요... 일단 머지하고 안되는것같으면 다시 볼게요

2022-09-28 09:04 UTC, peng-u-0807 approved these changes
네 PR이 너무 오래됐으니..일단 머지합시다

2022-09-28 09:12 UTC, merged