Fastlane CICD 구현
wafflestudio/snutt-ios pull request #160
Opened 2022-10-29 00:35 UTC by shp7724

Tag-based Deployment 방식으로 fastlane CI/CD workflow를 추가했습니다.

### Tag 문법 (regex)

- `(testflight|appstore)\/v(\d+)\.(\d+)\.(\d+)-(release|debug)\.(\d+)`
- 단, AppStore에 Debug 앱을 올리는 것은 인식하지 않습니다.
- 앱스토어나 테스트플라이트에 배포할 때 버전넘버와 빌드번호는 tag 이름을 따라갑니다.

### 환경 변수 (시크릿)

- `APP_STORE_CONNECT_KEY_CONTENT`: App Store Connect에서 발급받은 `앱 관리자` 권한의 API KEY
- `MATCH_DEPLOY_KEY`: Private Repo인 https://github.com/wafflestudio/wafflestudio-apple-certificates 에 접근하기 위한 Deploy Key
- `MATCH_PASSWORD`: Certificate 내용을 암호화하기 위한 match passphrase

2022-10-29 03:36 UTC, peng-u-0807 commented on .github/workflows/build.yml
> +          - '14.0.1'
저희 리팩토링 진행하면서 Xcode 버전은 13.4.1로 통일하지 않았나요? 13을 아예 끊고 14만 남겨두신 이유가 궁금합니당

2022-10-29 04:47 UTC, shp7724 commented on .github/workflows/build.yml
> +          - '14.0.1'
아 이건 나중에 revert하겠습니다.
지금 fastlane 때문에 계속 삽질중인데, 매번 버전 두개씩 도니까 macos 리소스가 부족해서 fastlane 실행이 너무 늦게되더라고요. 그래서 일단 하나만 돌게 해놨습니다.

2022-11-04 10:37 UTC, JSKeum requested changes

2022-11-04 10:37 UTC, JSKeum commented on .github/workflows/deploy-appstore.yml
> +      fail-fast: false # if 'true' then one failed job cancels all jobs remaining
주석을 보니 요건 true로 하는 게 맞는 것 같은데, false로 하신 이유가 무엇인가요??

2022-11-04 10:37 UTC, JSKeum commented on .github/workflows/deploy-appstore.yml
> +          echo "Not Implemented"
이 echo가 있는 이유는 뭔가요?

2022-11-04 10:37 UTC, JSKeum commented on SNUTT-2022/fastlane/.env.default
> +APP_STORE_CONNECT_KEY_ISSUER = "719d926e-ca2d-425d-a926-02d603c8a11f"
APP_STORE_CONNECT_KEY는 숨겨야 하는 정보 아닌가요??

2022-11-04 10:55 UTC, shp7724 commented on .github/workflows/deploy-appstore.yml
> +      fail-fast: false # if 'true' then one failed job cancels all jobs remaining
음 별 생각 없이 `build.yml`에서 가져온거였는데, 어차피 조합이 하나밖에 없어서 차이는 없을 듯 합니다.
생각해보니 애초에 matrix로 한 게 더 문제일 것 같네요. (배포 스크립트가 두 번 이상 돌면 안되니)

환경변수 사용하는 것으로 바꾸겠습니다.

2022-11-04 10:57 UTC, shp7724 commented on .github/workflows/deploy-appstore.yml
> +          echo "Not Implemented"
말그대로 `appstore` lane이 아직 준비가 안되었기 때문에 에러 메시지를 출력하도록 했습니다.

2022-11-04 10:59 UTC, shp7724 commented on SNUTT-2022/fastlane/.env.default
> +APP_STORE_CONNECT_KEY_ISSUER = "719d926e-ca2d-425d-a926-02d603c8a11f"
`APP_STORE_CONNECT_KEY_CONTENT` 는 숨겨야 하는 정보가 맞고 그래서 secret으로 들어가있습니다.
key id는 딱히 숨길 필요 없다고 생각했어요. 이것도 secret으로 할까요?

2022-11-05 03:14 UTC, shp7724 commented on SNUTT-2022/fastlane/.env.default
> +APP_STORE_CONNECT_KEY_ISSUER = "719d926e-ca2d-425d-a926-02d603c8a11f"
secret으로 해서 나쁠건 없을것같아 변경했습니다.

2022-11-05 04:02 UTC, shp7724 commented
`deploy-appstore.yml`을 지우고 `deploy.yml`로 합쳤습니다. 코드 중복이 너무 심해서요.

2022-11-06 09:49 UTC, JSKeum approved these changes
좋아요~

2022-11-06 10:27 UTC, merged