임시 강의 색상은 회색으로 뜨도록 수정
wafflestudio/snutt-ios pull request #167
Opened 2022-11-09 17:18 UTC by peng-u-0807

Resolves #156 
추가로 시간표 블록 UI 기존과 달랐던 부분 조금 수정했습니다.

2022-11-10 01:16 UTC, shp7724 approved these changes
👍

2022-11-10 01:32 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
>          // use custom color if colorIndex is zero
@shp7724 이전에 [관련 이슈](https://github.com/wafflestudio/snutt-ios/issues/158) 달아두었습니다

2022-11-10 01:35 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
>          // use custom color if colorIndex is zero
master 브랜치에서는 잘 되지 않나요? 아까 확인했었어요

2022-11-10 15:20 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
>          // use custom color if colorIndex is zero
@shp7724 master에서 확인해보니 잘 되네요. 전에 이슈 오픈했을 때 이후로 뭔가 변경사항은 없었을텐데 이슈에 자세한 설명이 없으니 잘 모르겠네요. 수정사항 커밋했습니다

2022-11-11 05:50 UTC, shp7724 reviewed
버그가 좀 있어서 직접 수정해서 푸시해보았고, 수정한 부분들에 대해 커멘트 남겼습니다.

2022-11-11 05:50 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
> -
이렇게 하면 실제 색상이 temporary 일 때는 밑에 있는 모든 규칙이 무시되는 문제가 있습니다.

`withTemporaryColor`의 로직을 수정하고, 기존의 getColor 우선순위 규칙에 따라 색상이 렌더링되도록 하는 게 나을 것 같습니다.

2022-11-11 05:50 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/LectureColorList.swift
> +            customColor.wrappedValue = .init(fg: color, bg: customColor.wrappedValue?.bg ?? theme.getColor(at: colorIndex.wrappedValue).bg)
default 값으로 `.temporary` 색상을 주었었는데, 이렇게 하니까 자잘한 버그가 보여서, `theme.getColor`에 의해 리턴되는 값으로 변경했습니다. 이 값은 `Lecture.getColor`가 리턴하는 값과 동일합니다.

(사실 이 부분 좀 지저분해서, 그냥 인자로 `lecture` 전체를 받게 하는게 더 깔끔할 것 같기도 하네요. 추후 리팩토링이 필요해보입니다.)

2022-11-11 06:56 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
> -
Uploading 화면 기록 2022-11-11 오후 3.54.40.mov…

재현 경로입니다

2022-11-20 15:02 UTC, shp7724 approved these changes
다른 문제 없으면 머지할까요?

2022-11-21 10:39 UTC, peng-u-0807 commented
@shp7724 올려주셨던 문제는 `lecture`이 "직접 선택하기 ColorPicker"에서 colorIndex만 0으로 초기화하기 때문입니다.
```
lecture.color = nil
lecture.colorIndex = 0
lecture.theme = .snutt
```
그렇기에 ColorPicker를 열기만 하고 아무런 선택을 하지 않을 경우 .snutt theme의 0번째 색깔인 흰색이 lecture의 color인 것처럼 그려집니다. "직접 선택하기 ColorPicker"를 열 때 lecture의 color를 기본 .temporary로 초기화해주는 쪽이 더 근원적인 해결 방법같아 이 방향으로 수정하였습니다

2022-11-21 14:23 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
> +
저는 직접 선택하기를 눌렀을 때 temporary color로 초기화해주는 게 맞는지 모르겠어요.

한번이라도 직접 색상을 선택한 경우 해당 색상은 서버로 저장되고, 나중에 언제든지 다시 선택할 수 있도록 구현해두었었는데, "직접 선택하기"를 탭할때마다 그게 초기화되면 불편할것같아요.

그밖에도 저장을 눌렀을 때 색이 제대로 반영이 안되는 이슈도 있는 것 같습니다.

https://user-images.githubusercontent.com/33917774/203077684-1a33b1be-e53c-4588-97da-0e37a0fe2fc3.mov

2022-11-25 15:50 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
> +
@shp7724 직접 선택하기를 누르고 색상을 선택하지 않더라도 Default 값을 들고 있는 것이 기존의 SNUTT 기획인데 딱히 이걸 바꿔야 할 이유는 모르겠어서 유지하는 쪽이 좋지 않을까 생각합니다. (유저가 기본 색상인 회색/검은색을 원하는 케이스도 고려해야 하고요) 그리고 저장을 누르기 전까지는 서버에 반영되지 않으니 우려하시는 부분은 괜찮을 것 같고, 버그 제보해주신건 customColor 중 bg 혹은 fg만 지정되지 않은 경우에 대한 문제였으므로 수정했습니다!

2022-11-25 16:27 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
> +
@peng-u-0807 비슷한 버그가 아직 남아있는 것 같아요 🤔

https://user-images.githubusercontent.com/33917774/204024614-6e80029a-b336-44aa-82e3-007e6070adf0.mov

제가 별로라고 생각했던 건 유저가 저장했던 색상이 "직접 선택하기"를 눌렀을 때 회색으로 override 된다는 점이었는데,
최근 커밋으로 그게 바뀌어서 좋은 것 같네요.

2022-11-25 17:27 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Lecture.swift
> +
+ 테스트 실패뜨는 것도 고쳐주시면 감사하겠습니다.

2022-11-26 10:47 UTC, shp7724 commented on SNUTT-2022/SNUTT/Assets/STColor.swift
>          }
좀 더 robust하고 간결하게 이건 어떨까요?

```swift
if str.count == 8 {
    str = String(str.suffix(6)) // drop alpha channel
}

if str.count != 6 {
    return self.init(uiColor: ...)  // fallback color
}
```

2022-11-26 10:53 UTC, shp7724 requested changes
https://user-images.githubusercontent.com/33917774/204085154-622a884a-20eb-4718-af0a-190964a91f98.mov

색상 선택이 안돼요 ㅠ_ㅠ

2022-11-26 14:35 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Assets/STColor.swift
>          }
색상 변경사항을 서버에 올릴 때 형식에 맞지 않을 경우 애초에 반영되지 않다보니 fallback color가 쓰일 일은 없을 것 같긴 하지만 혹시 모르니 추가해두면 좋을 것 같네요.👍

2022-11-26 16:43 UTC, shp7724 approved these changes
고생 많으셨습니다~ 👍

2022-11-26 16:45 UTC, merged