Firebase Crashlytics 연결
wafflestudio/snutt-ios pull request #183
Opened 2022-11-22 14:19 UTC by shp7724

- debug symbol 파일을 crashlytics에 업로드하는 빌드 스크립트를 추가했습니다.

2022-11-25 06:52 UTC, peng-u-0807 requested changes

2022-11-25 06:52 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
> -		B87DF6F129150A00008BB95B /* PopupService.swift in Sources */ = {isa = PBXBuildFile; fileRef = B87DF6F029150A00008BB95B /* PopupService.swift */; };
팝업 관련 파일들이 모두 지워졌습니다. 확인 부탁드려요! 그리고 가능하시다면 `Package.resolved`도 제외 부탁드립니다.

2022-11-25 07:34 UTC, shp7724 commented on SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
> -		B87DF6F129150A00008BB95B /* PopupService.swift in Sources */ = {isa = PBXBuildFile; fileRef = B87DF6F029150A00008BB95B /* PopupService.swift */; };
Popup 관련 항목들이 pbxproj 파일에 두 번씩 중복해서 들어가 있더라고요. xcode로 열어보시면 안전하게 잘 들어있습니다.

---

`Package.resolved`는 일부러 다시 포함시킨건데, 전에 제외하셨던 이유가 있었나요?

`Package.resolved` 파일을 제외하면 github CICD 환경에서 빌드할때 최신 버전의 의존성을 다운받기 때문에 xcode 13.4.1 버전과 호환이 안맞는 문제가 있었습니다. 그리고 [애플 공식 문서](https://developer.apple.com/documentation/xcode/making-dependencies-available-to-xcode-cloud)에서도 포함하도록 권장하고 있구요.

> If you use Swift package dependencies in your project, make sure to include the Package.resolved file in your Git repository and commit any changes to it. Don’t include the file in your .gitignore file.

2022-11-25 07:57 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
> -		B87DF6F129150A00008BB95B /* PopupService.swift in Sources */ = {isa = PBXBuildFile; fileRef = B87DF6F029150A00008BB95B /* PopupService.swift */; };
아, 중복 파일이었군요. 답변 감사합니다👍

2022-11-25 08:06 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "15.1.0"
페이스북 sdk 버전업은 의도된 부분인가요?

2022-11-26 11:03 UTC, JSKeum approved these changes

2022-11-26 11:09 UTC, merged