[Fix] Weekday not Automatically Aligning #198
wafflestudio/snutt-ios pull request #199
Opened 2023-01-02 18:48 UTC by chaemin2001

- 자동 맞춤 시에 요일도 맞춰지도록 수정했습니다.
- 주말에 일정이 없는 경우에는 기존과 같게 주중만 표시되도록, 그리고 토요일에 일정이 있다면 월-토, 일요일에 일정이 있다면 토요일과 상관없이 월-일로 보이도록 했습니다.

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-03 at 03 43 29](https://user-images.githubusercontent.com/74291744/210269069-5cce5bdd-581f-48ac-a38d-a893854c790e.png)

(제가 아직 코드를 완벽하게 파악하지 못해서 적당한 파일을 수정하지 못했을 수도 있을 것 같습니다. 피드백 주시면 반영하겠습니다!)

2023-01-03 12:54 UTC, shp7724 requested changes
첫 PR 올리시느라 고생 많으셨습니다! 🎉

전반적으로 로직상 문제는 없어보이지만, [빌드가 실패](https://github.com/wafflestudio/snutt-ios/actions/runs/3824547594/jobs/6506784672)해서 핵심 로직쪽은 제대로 확인하지 못했습니다.

리뷰 참고해서 빌드 고쳐주신 뒤, 다시 리뷰 요청 해주시면 다시 확인해보겠습니다!

2023-01-03 12:54 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Timetable.swift
> +
여기서 Nullish coalescing을 쓰기보다는 `Weekday?`를 리턴하는게 더 좋을 것 같습니다. `TimetableUtils.getVisibleWeeks`에서 optional은 잘 처리되고 있으니까요!

2023-01-07 08:02 UTC, chaemin2001 commented on SNUTT-2022/SNUTT/Models/TimetableConfiguration.swift
>      }
앗 처음에 weekCount를 수정하려다가 새 변수를 선언하다가 까먹은 것 같습니다. 돌려놓았습니다.

2023-01-07 08:02 UTC, chaemin2001 commented on SNUTT-2022/SNUTT/Models/Timetable.swift
> +
넵 감사합니다

2023-01-07 13:32 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +    }
이 [슬랙 스레드](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1670654380270119?thread_ts=1670654227.759719&cid=C0PAVPS5T)에 따르면 여기서 [월화수목금]이 리턴되어야 할 것 같습니다!

2023-01-07 17:27 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
어차피 자동맞춤 On이라면 아래와 같으므로
- default: 월-금
- 최대 일정이 토요일까지면 월-토/일요일까지면 월-일

lastWeekDay를 체크하지 않고 아래와 같은 방향으로 수정하면 간단하지 않을까요?
``` Swift
if weekDay.contains(.sun) -> .mon ~ .sun
else if weekDay.contains(.sat) -> .mon ~ .sat
else -> .mon  ~ .fri
```

2023-01-08 03:35 UTC, chaemin2001 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
그러면 좋을 것 같았는데 일정이 포함되어있는 WeekDay를 모두 리턴해주는 함수를 찾지 못했습니다ㅜ 따로 선언해두었을까요?

2023-01-08 03:37 UTC, chaemin2001 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +    }
넵!

2023-01-08 04:09 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
`Weekday.allCases` 같은걸로 사용하면 되지 않을까요?

2023-01-08 04:58 UTC, peng-u-0807 approved these changes

2023-01-08 05:03 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
@shp7724 저도 그쪽으로 생각해봤는데 max로 구하나 contains로 구하나 O(n)인 점은 동일해서 채민님께서 구현해주신대로도 괜찮을 것 같아요.

2023-01-08 05:09 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
조금 다른 얘기지만 덧붙이자면 반환하는 부분에 [.mon ~ .sun]을 일일히 넣어주기보다는 아래와 같이 수정해도 괜찮을 것 같아요
``` Swift
...
if lastWeekDay == .sun {
    return Weekday.allCases
}
if lastWeekDay == .sat {
    return Weekday.allCases.dropLast()
}
return Weekday.allCases.dropLast(2)
```

2023-01-08 05:11 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        return weeks.count
그리고 이 부분은 `weeks` 사용 없이 한 줄로 정리하면 어떨까요
``` Swift
getVisibleWeeks(current: current, config: config).count
```

2023-01-08 05:30 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
흠 최대 N이 7밖에 안돼서 시간복잡도보다는 코드 간결함이 더 중요한 팩터가 아닐까 하네요
그래서 전 유림님이 처음에 제시하신 안이 더 좋아보이긴 했습니다.

그리고 저는 명시적으로 [.mon ~ .sun] 넣어주는게 직관적으로 이해하기에 더 괜찮은것같아요
`Weekday.allCases`라고 하면 월요일부터 시작인지 일요일부터 시작인지 좀 헷갈리는 느낌이 있어서..

2023-01-08 05:56 UTC, chaemin2001 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        }
하하 .. 그럼 일단은 이렇게 두고 좀 더 나은 방법을 고민해보겠습니다

2023-01-08 16:12 UTC, chaemin2001 commented on SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
> +        return weeks.count
넵! 감사합니다

2023-01-09 04:52 UTC, shp7724 approved these changes

2023-01-09 07:17 UTC, merged