Fix `PopupDto` field name + display logic
wafflestudio/snutt-ios pull request #296
Opened 2024-04-10 14:41 UTC by peng-u-0807

### 수정사항
- `hidden_days`랑 `image_url` camelCase로 변경
  - 하는 김에 다른 필드명도 동일하게 수정했어요
- [팝업 로직 변경](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1712758540760669?thread_ts=1712730879.668129&cid=C0PAVPS5T)

2024-04-10 14:52 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Popup.swift
>          return Date().daysFrom(lastUpdate) > hiddenDays
이렇게 해도 될거같아여 
```suggestion
        return Date().daysFrom(lastUpdate) >= hiddenDays
```

2024-04-10 14:53 UTC, shp7724 reviewed
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1711187135590259?thread_ts=1711185455.259979&cid=C0PAVPS5T

이것도 하긴 해야하는데... 🙄

2024-04-10 14:53 UTC, peng-u-0807 commented
@shp7724 앗 저런 태스크까지 딸려있는 줄은 몰랐네....

2024-04-10 14:57 UTC, shp7724 commented
@peng-u-0807 

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1711185907487529?thread_ts=1711185455.259979&cid=C0PAVPS5T

그냥 여기서 로컬 팝업/서버 팝업 image uri 달라지면 서버쪽 dto 쓰도록 변경해줄수있어? 한두줄이면 될듯

2024-04-13 06:32 UTC, shp7724 commented on SNUTT-2022/SNUTT/Repositories/Dto/PopupDto.swift
> +    let dontShowForWhile: Bool?
`PopupDto`에서는 `key`, `imageUri`, `hiddenDays`만 남기는 게 어떨까요

2024-04-13 06:32 UTC, shp7724 commented on SNUTT-2022/SNUTT/Repositories/Dto/PopupDto.swift
> +    let dontShowForWhile: Bool?
그리고 `dismissPopup` 쪽에서도 `[PopupMetadata]` 저장하도록 바꿔야하지 않나요?
그냥 PopupDto는 서버 데이터로만 일시적으로 활용하고, Metadata만 로컬에 저장하도록 바꾸는게 좋을 것 같아요

2024-04-16 08:10 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Repositories/Dto/PopupDto.swift
> +    let dontShowForWhile: Bool?
@shp7724 반영해서 수정했슴다

2024-04-25 17:34 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        if hiddenDays == 0 { return dismissedAt == nil }
아냐 이거 hiddenDays == 0이면 무조건 보여주도록 하다보니까 이전에 코멘트 남겨준 것처럼 hiddenDays >= 0으로만 검사하면 hiddenDays == 0으로 내려온 팝업은 닫기 버튼을 눌러도 영원히 보여서...위의 !dontShowForWhile처럼 dismiss timestamp 찍혀있는지 확인 필요하더라구

2024-04-25 23:43 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        if hiddenDays == 0 { return dismissedAt == nil }
L19 때문에 dismissedAt 은 이미 nil이 아닌거 아니야?

2024-04-28 06:51 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        if hiddenDays == 0 { return dismissedAt == nil }
엉 마자 nil이 아니어야 hiddenDays는 0인데, 이미 한번 "당분간 보지 않기"를 누른 팝업인 셈이니까 안보여주는게 맞는거고...
이 줄이 없고 그 다음줄만 검사하면 `Date().daysFrom(lastUpdate) >= hiddenDays`가 항상 true가 되니까 문제가 생긴다는 뜻이었으

2024-04-28 06:52 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        if hiddenDays == 0 { return dismissedAt == nil }
엉 마자 nil이 아니어야 hiddenDays는 0인데, 이미 한번 "당분간 보지 않기"를 누른 팝업인 셈이니까 안보여주는게 맞는거고...
이 줄이 없고 그 다음줄만 검사하면 `Date().daysFrom(lastUpdate) >= hiddenDays`가 항상 true가 되니까 문제가 생긴다는 뜻이었으

2024-04-30 17:54 UTC, shp7724 requested changes

2024-04-30 17:54 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Popup.swift
이렇게 하는거 어때 (PopupService 쪽도 맞춰서 수정 필요)

```swift
struct Popup: Identifiable {
    let id: String
    let imageURL: String
    let hiddenDays: Int?
    private(set) var dismissedAt: Date?
    private(set) var dontShowForWhile: Bool

    var shouldShow: Bool {
        guard dontShowForWhile else { return dismissedAt == nil }
        guard let dismissedAt else {
            assertionFailure()
            return true
        }
        guard let hiddenDays else {
            // If hiddenDays is nil, `dontShowForWhile` means "never show this popup again"
            return false
        }
        return Date().daysFrom(dismissedAt) >= hiddenDays
    }

    mutating func markAsDismissed(dontShowForWhile: Bool) {
        if hiddenDays == 0 {
            // If hiddenDays is 0, always show the popup next time
            self.dontShowForWhile = false
            dismissedAt = Date()
            return
        }
        self.dontShowForWhile = dontShowForWhile
        dismissedAt = Date()
    }

    mutating func resetDismissedAt() {
        guard !dontShowForWhile else { return }
        dismissedAt = nil
    }
}

extension Popup {
    init(from dto: PopupDto) {
        id = dto.key
        imageURL = dto.imageUri
        hiddenDays = dto.hiddenDays
        dismissedAt = nil
        dontShowForWhile = false
    }

    init(from metadata: PopupMetadata, imageUri: String) {
        id = metadata.key
        imageURL = imageUri
        hiddenDays = metadata.hiddenDays
        dismissedAt = metadata.dismissedAt
        dontShowForWhile = metadata.dontShowForWhile ?? false
    }
}
```

2024-05-15 14:19 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Popup.swift
수정했슴다

2024-05-15 14:38 UTC, chaemin2001 approved these changes

2024-05-15 17:06 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        guard let dismissedAt = dismissedAt else { return true }
`= dismissedAt` 지워도 되고
assertionFailure 넣어줘여...

2024-05-15 17:07 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        guard let dismissedAt = dismissedAt else { return true }
dismissedAt이 nil인 케이스가 있나?

2024-05-16 04:37 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        guard let dismissedAt = dismissedAt else { return true }
`dontShowForWhile`이 true면 `dismissedAt`은 항상 nil 맞아
+ 반영했슴다

2024-05-16 04:42 UTC, shp7724 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        guard let dismissedAt = dismissedAt else { return true }
항상 nil 아닌거 맞다는거지? ㅋㅋㅋ

2024-05-16 04:42 UTC, shp7724 approved these changes

2024-05-16 04:46 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Models/Popup.swift
> +        guard let dismissedAt = dismissedAt else { return true }
ㅇ ㅏ 어어ㅋㅋㅋㅋㅋ

2024-05-16 05:07 UTC, merged