iOS14/15 빌드 테스트 CI [SNUTT-411]
wafflestudio/SNUTT-iOS pull request #57
Opened 2022-03-23 14:34 UTC by shp7724

# 수정 내용
- iOS 14 / 15 빌드 테스트를 위한 github actions를 추가했습니다.

2022-03-23 14:54 UTC, shp7724 commented
일단 xcode 13에서 iOS 14 타겟 빌드는 실패하는 것 같습니다.

```
xcodebuild -destination 'platform=iphonesimulator,os=14.5,name=iPhone 12' -scheme SNUTT -configuration Debug test
```

```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iphonesimulator, name:iPhone 12 }

	Unsupported device specifier option.
	The device “iPhone 12” does not support the following options: os
	Please supply only supported device specifier options.

	Available destinations for the "SNUTT" scheme:
		{ platform:iOS Simulator, id:6E612B12-333B-4F9E-B75B-99F11EFF00E8, OS:15.2, name:iPad (7th generation) }
		{ platform:iOS Simulator, id:F8313552-AA65-492A-BA83-0B09FB94FB7B, OS:15.2, name:iPad (8th generation) }
		{ platform:iOS Simulator, id:E9C25C9E-CFCA-4057-8203-80A15851A7EF, OS:15.2, name:iPad (9th generation) }
		{ platform:iOS Simulator, id:89EAD0AB-A[14](https://github.com/wafflestudio/SNUTT-iOS/runs/5662271507?check_suite_focus=true#step:6:14)2-4D3A-A62A-389255DBEADA, OS:[15](https://github.com/wafflestudio/SNUTT-iOS/runs/5662271507?check_suite_focus=true#step:6:15).2, name:iPad Air (3rd generation) }
		{ platform:iOS Simulator, id:045AA8D4-6938-465B-90FB-362F[16](https://github.com/wafflestudio/SNUTT-iOS/runs/5662271507?check_suite_focus=true#step:6:16)60B22F, OS:15.2, name:iPad Air (4th generation) }
		{ platform:iOS Simulator, id:7A1DE916-7B51-4F19-99DB-2B083F7DA581, OS:15.2, name:iPad Pro (9.7-inch) }
		{ platform:iOS Simulator, id:3AB6405F-568F-4756-AE91-162916EBCA19, OS:15.2, name:iPad Pro (11-inch) (2nd generation) }
		{ platform:iOS Simulator, id:F1CCF362-D95B-4A74-A799-805BDE29A706, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
		{ platform:iOS Simulator, id:7AF452F2-DA26-4AA3-9020-9CD800DEC0CE, OS:15.2, name:iPad Pro (12.9-inch) (4th generation) }
		{ platform:iOS Simulator, id:7CB14E7C-5834-4685-B9C1-7D956B2F0BE4, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
		{ platform:iOS Simulator, id:D2DCAD01-3535-482A-9DEE-360CF10C9FEE, OS:15.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:D211B988-BEF9-4A39-8A97-A9BBF823F27C, OS:15.2, name:iPhone 8 }
		{ platform:iOS Simulator, id:352F6FD0-855E-4AE8-BA6F-102C8D3971A2, OS:15.2, name:iPhone 8 Plus }
		{ platform:iOS Simulator, id:16DB7616-C5B9-4E45-8A9A-71253FF81A9C, OS:15.2, name:iPhone 11 }
		{ platform:iOS Simulator, id:146AC047-AC86-4BBF-B6D3-8D08520EDDC9, OS:15.2, name:iPhone 11 Pro }
		{ platform:iOS Simulator, id:25A9E533-83F9-418B-BA37-3F3BDB24CE56, OS:15.2, name:iPhone 11 Pro Max }
		{ platform:iOS Simulator, id:88E5FE53-731E-4FEC-96A2-C0ED9D4A4DC8, OS:15.2, name:iPhone 12 }
		{ platform:iOS Simulator, id:9F7C9DC4-32A5-4467-97FE-35FF3B04D690, OS:15.2, name:iPhone 12 Pro }
		{ platform:iOS Simulator, id:4B05A8EF-99D6-4871-A7BD-34616DE09596, OS:15.2, name:iPhone 12 Pro Max }
		{ platform:iOS Simulator, id:F4293008-6BC1-48C3-8792-05D045F90123, OS:15.2, name:iPhone 12 mini }
		{ platform:iOS Simulator, id:A45D5252-7A5D-45C3-8454-88FDA7DD11C6, OS:15.2, name:iPhone 13 }
		{ platform:iOS Simulator, id:F005A74C-4CD2-4447-9365-02D1CC5302AB, OS:15.2, name:iPhone 13 Pro }
		{ platform:iOS Simulator, id:E649F663-CA2A-4366-9733-ED2C7C0A6574, OS:15.2, name:iPhone 13 Pro Max }
		{ platform:iOS Simulator, id:81E6D631-0C67-49B0-8042-55CBEB4AC2F9, OS:15.2, name:iPhone 13 mini }
		{ platform:iOS Simulator, id:0805FC8A-E8C3-42B4-9EF2-8963B51BD[17](https://github.com/wafflestudio/SNUTT-iOS/runs/5662271507?check_suite_focus=true#step:6:17)6, OS:15.2, name:iPhone SE (2nd generation) }
		{ platform:iOS Simulator, id:DD06E861-[30](https://github.com/wafflestudio/SNUTT-iOS/runs/5662271507?check_suite_focus=true#step:6:30)D6-4C8C-A7DE-90BE3C0FFD96, OS:15.2, name:iPod touch (7th generation) }

	Ineligible destinations for the "SNUTT" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
```

2022-03-23 15:06 UTC, shp7724 commented
https://www.githubstatus.com/

깃헙 서버에 문제가 있어 action 실행이 안되네요.
추후에 리뷰 요청하겠습니다.

2022-03-28 11:17 UTC, JSKeum requested changes

2022-03-28 11:17 UTC, JSKeum commented on .github/workflows/build.yml
> +    - uses: maxim-lobanov/setup-xcode@v1.2.3
`maxim-lobanov/setup-xcode` 를 꼭 사용해야 하나요? 어떤 setup인가요?

2022-03-28 11:17 UTC, JSKeum commented on .github/workflows/build.yml
> +        command: ['test']
이름은 'build-and-test' 인데 test 밖에 없네요. build도 추가하면 좋겠어요~

2022-03-28 11:17 UTC, JSKeum commented on .github/workflows/build.yml
> +        upload-logs: always
log를 업로드해야 하는 이유가 뭔가요?

2022-03-28 16:19 UTC, shp7724 commented on .github/workflows/build.yml
> +    - uses: maxim-lobanov/setup-xcode@v1.2.3
github macos 환경에 여러 버전의 xcode가 preinstalled 되어 있는데, 그 중 하나를 선택해주는 action입니다. `xcode-select`의 convenience wrapper라고 보시면 될 것 같습니다.

2022-03-28 16:27 UTC, shp7724 commented on .github/workflows/build.yml
> +        command: ['test']
`test`가 `build`도 포함하지 않나요? (테스트 하려면 빌드부터 해야하니까..?)

[실패한 action 로그](https://github.com/wafflestudio/SNUTT-iOS/runs/5631728469?check_suite_focus=true) 보시면 `test` 커맨드만 사용해도 compiler 에러 발생하는 것 확인하실 수 있습니다.

2022-03-29 01:18 UTC, JSKeum commented on .github/workflows/build.yml
> +        command: ['test']
`test`에서 돌아가는 build는 `build-for-testing`으로 Debug 앱이나 Prod 앱에서 사용하는 build랑 다릅니다. (Xcode 안에서도 build for test를 돌려볼 수 있습니다) 오직 unit test를 위한 build이기 때문에, debug, prod 앱을 위한 build는 따로 해줘야 합니다.

2022-03-29 01:28 UTC, JSKeum commented on .github/workflows/build.yml
> +    - uses: maxim-lobanov/setup-xcode@v1.2.3
`xcode-select` 라는 단순한 스크립트인데 굳이 의존성을 추가할 필요가 있을까요? 스크립트를 명확히 볼 수 있게 
` - run: xcode-select ${{ matrix.xcode }}` 같이 하는게 나아 보입니다. (run 안에 matrix 변수 문법은 맞는지 모르겠네요)

2022-03-29 01:28 UTC, JSKeum commented on .github/workflows/build.yml
> +        upload-logs: always
로그는 artifacts를 다운받아서 보는 것보다 Action 링크 들어가서 보는게 효율적으로 보입니다. 굳이 artifact 업로드하느라 비용(action 시간, 100kb가 넘는 artifact 용량)을 쓸 필요는 없을 것 같아요

2022-03-29 01:28 UTC, JSKeum commented on .github/workflows/build.yml
> +        command: ['test']
https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-PRODUCT
여기 참고해주세요~

2022-03-29 01:45 UTC, shp7724 commented on .github/workflows/build.yml
> +    - uses: maxim-lobanov/setup-xcode@v1.2.3
정확한 커맨드는 `xcode-select --switch /Applications/Xcode ${{ 버전 }}.app/Contents/Developer` 인 것 같습니다.

가상머신 상의 Xcode 절대경로를 지정해줘야 한다는 점이 약간 찝찝하기도 하고, `latest-stable`이나 [SemVer](https://devhints.io/semver) 같은 편의기능도 지원해줘서 이 방식이 오히려 더 reliable할 것 같은데 어떻게 생각하시나요?

2022-03-30 01:18 UTC, JSKeum commented on .github/workflows/build.yml
> +    - uses: maxim-lobanov/setup-xcode@v1.2.3
Xcode 절대경로를 지정하는건 의존성 안에서도 마찬가지일텐데 찝찝한 이유는 무엇인가요? 말씀하신대로 단순한 버전 선택 이외의 다른 옵션들을 쉽게 추가할 수 있다는 장점은 있는 것 같은데, 그 옵션들이 필요할지 모르겠어요. 제가 의존성을 제거하고 `xcodebuild` 스크립트를 풀어서 쓰면 좋겠다는 가장 큰 이유는, 코드만 보고 정확하게 어떤 명령어가 실헹되는지 알고 싶어서입니다.

2022-03-30 01:37 UTC, shp7724 commented on .github/workflows/build.yml
> +    - uses: maxim-lobanov/setup-xcode@v1.2.3
네 무슨 말씀인지 알겠습니다. 반영하도록 하겠습니다!

2022-03-30 11:47 UTC, JSKeum approved these changes

2022-03-30 12:16 UTC, merged