feat: create TimetableList view
wafflestudio/SNUTT-iOS pull request #58
Opened 2022-03-23 15:58 UTC by shp7724

# 수정 사항
- #56 에 의존하는 PR입니다.
- `TimetableList`와 `TimetableListCell`, 그리고 임시로 `LectureDetails` 뷰를 추가했습니다.
- 모델은 따로 추가하지 않아서 Text 값들은 전부 하드코딩했습니다.

![image](https://user-images.githubusercontent.com/33917774/159741583-8ae8e91f-98bb-4378-88d7-e1f17a9b52e1.png)
![image](https://user-images.githubusercontent.com/33917774/159741596-30b33f23-be22-485d-a08f-15e607c35af4.png)

2022-03-23 16:01 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +}
자주 사용하는 `Font`나 `Color`들을 깔끔하게 관리하고 싶은데, 디자인 시스템이 아직 완전히 정리된게 아니다보니 어떤 방식이 좋을지 고민중입니다. 의견 부탁드려요.

2022-03-28 11:23 UTC, JSKeum requested changes

2022-03-28 11:23 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/LectureDetails.swift
> +struct LectureDetails: View {
파일 이름 `LectureDetailList` 와 view component 이름이 일치하면 좋겠습니다~

2022-03-28 11:23 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
여기 ZStack의 개수를 하드코딩하지 말고 `TimeTableList`의 파라미터로 받게 할 수는 없을까요?

2022-03-28 11:23 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +}
폰트 설정을 따로 파일 만들어서 관리하는게 어떨까요?

2022-03-28 11:23 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +    func detailRow(imageName: String, text: String) -> some View {
여기는 View 컴포넌트를 따로 만들지 않고 `@ViewBuilder func`으로 구현한 이유가 무엇인가요?

2022-03-28 11:24 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +}
outdated돼서 못봤네요. 리뷰 남긴 것처럼 파일을 따로 만들어서 관리하면 좋겠어요

2022-03-28 11:26 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/LectureDetails.swift
> +struct LectureDetails: View {
아 위의 주석에 적힌 파일 이름과 밑의 preview 이름이 다른거군요. `LectureDetails`로 수정하신 이유는 피그마에 그렇게 적혀 있기 때문인가요?

2022-03-28 11:28 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +struct TimetableList: View {
이렇게 Container 또는 Scene 역할을 하는 View는 따로 분류를 해서 관리하면 좋겠네요. `Components/Scenes `아니면 `Components/Containers` 같이

2022-03-28 15:24 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
우선 지금은 dummy data 넣느라 이렇게 해두신 것 같은데 나중에는 이렇게 수정할 수도 있을 것 같네요

```
var body: some View {
    List(lectures) { lecture in
        ZStack {
            NavigationLink {
                LectureDetails()
            } label: {
                EmptyView()
            }
            // workarounds to hide arrow indicator
            .opacity(0.0)

            TimetableListCell(lectureInfo: lecture)
        }
    }.listStyle(GroupedListStyle())
}
```

2022-03-28 15:39 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +}
따로 파일로 관리하자는 의견에는 저도 동의합니다.
이런거 모아놓는 폴더를 따로 만들면 좋을것같은데 폴더명/파일명을 뭘로하면 좋을까요?
일단 지금 생각나는건 `Common/Fonts.swift` 정도...네요.

---

그리고 제가 작성한 방식은 기본 시스템 폰트와 구분이 안된다는 단점이 있어서요.

```swift
extension Font {
    struct STFont {
        ...
    }
}
```

또는 
```swift
struct STFont {
    ...
}
```

요런식으로 별도의 네임스페이스?로 관리해도 좋을 것 같긴 합니다.

2022-03-28 15:52 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/LectureDetails.swift
> +struct LectureDetails: View {
아, 파일명 리팩토링 했는데 주석은 안바뀌었나보네요.
맨 처음에 `LectureDetailList`로 했던 건 `List`를 사용해서 구현하려고 했던 건데, 
`StackViews in ScrollView` 방식으로 구현하는게 나을 수도 있겠다는 생각이 들어 `LectureDetails`로 고친거였습니다.

지금은 잠정적으로 만들어둔거고, 실제 구현을 어떻게 하는지에 따라 뷰 이름 확정하면 될 것 같습니다.

2022-03-28 15:55 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
@JSKeum @peng-u-0807 님이 말씀하신것처럼 나중에는 어차피 `AppState`에 저장된 데이터로 populate하게 될 것 같아서 저렇게 해두었습니다! 지금 단계에서는 큰 의미 없을 것 같아서요.

2022-03-28 15:59 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +    func detailRow(imageName: String, text: String) -> some View {
View 컴포넌트를 따로 만들기에는 너무 작은 단위이기도 하고, 현재 Figma 디자인상으로는 `detailRow`가 다른 뷰에서 재사용될 일이 없을 거라고 생각해서 `ViewBuilder` 방식으로 구현했습니다.

2022-03-28 16:04 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +struct TimetableList: View {
현재 폴더구조가 아래처럼 되어 있는데, Components 폴더 안에 Scenes 폴더를 따로 만들자는 말씀이실까요?

```
|- Views
    |- Components
    |- Scenes
```

2022-03-30 01:38 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +}
`extension Font`를 사용하는게 깔끔해 보였는데, 말씀하신대로 커스텀 폰트를 명확히 구분하려면 `struct STFont`를 새로 선언하는게 좋은 것 같네요. extension 안에 넣지 말고 새로운 객체로 선언하는게 더 나아 보입니다!

2022-03-30 01:45 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
state를 관리하는 역할을 맡는 특정한 컴포넌트를 제외하면 모든 뷰 컴포넌트는 stateless하게 만들면 좋겠습니다. stateless라는 말은 `@State`와 같은 state 변수를 갖지 않고, 부모에게서 받은 데이터를 보여주는 역할만 하는 거죠. stateless한 컴포넌트는 그래서 `AppState`나 기타 다른 state layer와는 독립적으로 구현되고 테스트될 수 있습니다. 더미데이터를 쓸 때나 실제 데이터를 쓸 때나 코드가 달라지지 않죠.
` ForEach(1 ..< 10)` 로 구현한 방식은 stateful한 방식이고, 
(이 View에는 state를 갖지 않게 하면)`List(lectures) {`로 구현한 방식은 steteless한 방식입니다

2022-03-30 01:47 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift
> +    func detailRow(imageName: String, text: String) -> some View {
좋아요~ 앞으로도 재사용되지 않고 작은 단위는 내부에서 구현하는 것으로 해요

2022-03-30 01:51 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
다시 보니까 이 `TimetableList`가 컨테이너(stataful한) 역할을 하는군요. 그러면 `List(lectures`로 구현하고, `let lectures = []`로 변수로 두는게 나아 보이네요. 아니면 `TimetableList` 을 감싸는 Page(Scene) 단위의 컨테이너를 두면 어떨까요? `MyTimetableListScene` 이런 식으로

2022-03-30 02:18 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
`MyTimetableListScene`으로 래핑하는 건 좋은 것 같습니다. 파일명이 Scene으로 끝나는 건 `Scenes` 폴더에 넣고, 나머지는 `Components` 폴더에 넣으면 되겠네요. 

`Components` 중에서도 Stateless한 뷰와 Stateful한 뷰를 구분하는게 나을까요? 관련해서 자주 쓰이는 네이밍 컨벤션이나 디렉토리 구조같은게 있는지 궁금하네요.

2022-03-30 11:52 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
복잡한 state가 필요하지 않는 한, Components안에 있는 건 모두 Stateless하게끔 하는게 좋아 보입니다. 근데 구현하다보면 Components 안에도 꼭 state 선언이 필요할 때가 있을 수도 있는데, 그때는 예외적으로 쓰도록 합시다.
이와 관련된 좋은 글로 Redux를 만든 Dan Abramov가 쓴 블로그 글이 있습니다. [링크](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

2022-03-31 09:08 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +            ForEach(1 ..< 10) { _ in
@JSKeum 위에서 논의한 내용 반영했습니다. 확인 부탁드려요.

2022-04-01 12:49 UTC, JSKeum approved these changes

2022-04-01 12:49 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Scenes/MyTimetableListScene.swift
> +    let myDummyLectureList = DummyAppState.shared.lectures
우리 아키텍쳐에 따르면 여기서 데이터는 ViewModel에서 불러오는게 맞는데, 아직 ViewModel이 없으니 일단 이렇게 해두고 나중에 수정해요~

2022-04-01 12:50 UTC, merged