탭뷰 및 네비게이션 바 UI 구현 [SNUTT-421]
wafflestudio/SNUTT-iOS pull request #63
Opened 2022-04-08 01:21 UTC by shp7724

# 수정 내용
- 탭뷰와 네비게이션 바 UI를 구현했습니다.
- UI 구현을 위해 여러 아이콘 이미지를 추가했습니다.

# 실제 SNUTT와 다른 점

- 탭뷰 안에 네비게이션 뷰가 포함됩니다(i.e. 탭이 4개니 네비게이션 뷰도 4개). 그렇기 때문에 탭뷰에서 하위 뷰로 navigate하면 하단 탭바가 화면에 계속 보이는 상황입니다. 그러나 실제 SNUTT의 작동 방식과 동일하게 구현하려면 **`LectureDetails` 뷰에 진입할 때에는 탭바를 숨겨 주어야 합니다.**
- UIKit에서는 `hidesBottomBarWhenPushed` 속성을 사용하면 쉽게 구현이 가능하지만, SwiftUI에서는 해당 기능이 구현되지 않은 것 같습니다. 이에 대한 Workaround로는,
    1. [SwiftUI-Introspect](https://github.com/siteline/SwiftUI-Introspect)라는 라이브러리를 사용해서 강제로 저 속성을 `true`로 바꿔준다.
    2. (식샤에서 사용하는 방법) `GeometryReader` 등을 사용하여 하단 탭을 직접 구현한다.
    3. 그냥 그대로 둔다.
    4. `LectureDetails`를 push가 아닌 present 방식으로 전환한다.
- 1, 2번은 리팩토링의 취지에 맞지 않는 것 같아서 일단 3번으로 해두었는데요, 나중에는 4번으로 하는것도 자연스러울 것 같습니다.

# 다크모드

- 이번에 import한 아이콘은 피그마에 흰색 버전이 존재하지 않아서 다크모드 대응을 하지 않았습니다. 제가 직접 색을 변환할 수도 있지만, 디자이너님과 먼저 논의하는게 순서인것같아서 그렇게 하지는 않았습니다.
- 앞으로도 이런 상황이 종종 있을 것 같은데, 어떻게 하는게 좋을까요?
    1. 다크모드 아이콘이 필요할 때마다 디자이너님께 요청
    2. 다크모드 아이콘이 필요할 때마다 직접 색변환
    3. 일단 라이트모드로만 구현하고, 나중에 다크모드 디자인 나오면 한번에 적용

# 데모

https://user-images.githubusercontent.com/33917774/162342918-3540ac78-219a-4b2d-8c4a-0e8110ba55b4.MP4

2022-04-08 01:24 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/SNUTTApp.swift
> +
한 가지 궁금한 점: 이런 간단한 State도 `AppState`에 들어가는게 좋을까요?

2022-04-16 03:51 UTC, JSKeum commented
다크모드는 이미지 / 폰트 색을 두 가지로 적용할 수 있게 만들고, 실제 에셋은 라이트(기본)으로 해두면 될 것 같아요. 다크모드 에셋 만드는게 큰 일이라서, 나중에 디자이너분이 다 만드시면 그때 적용하도록 하지요

2022-04-16 03:52 UTC, JSKeum commented
![Screen Shot 2022-04-16 at 12 52 13 PM](https://user-images.githubusercontent.com/54926767/163660426-18e6b859-8448-4e0b-a87a-31cfc704870b.png)
present 방식으로 바꾸는 건 작업이 많이 필요한가요?

2022-04-16 04:06 UTC, JSKeum requested changes

2022-04-16 04:06 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/SNUTTApp.swift
> +    let symbolName: String
symbolName을 좀더 type safe하게 String 말고 enum으로 선언하는게 어떨까요?
```
enum SymbolName: String {
    case timetable
    case search
    case review
    case settings
}
```

2022-04-16 04:22 UTC, shp7724 commented
> ![Screen Shot 2022-04-16 at 12 52 13 PM](https://user-images.githubusercontent.com/54926767/163660426-18e6b859-8448-4e0b-a87a-31cfc704870b.png)
> 
> present 방식으로 바꾸는 건 작업이 많이 필요한가요?
> 
> 

아뇨, present 방식으로 하기로 한다면 바로 바꿀 수 있습니다.

2022-04-16 04:23 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/SNUTTApp.swift
> +    let symbolName: String
좋아요. 반영하겠습니다.

2022-04-24 04:30 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/SNUTTApp.swift
> +
TabView에서 선택된 탭 말씀하시는 것이라면 현재 선택된 화면이 무엇인지에 따라 해야 할 액션이 달라지는 경우가 있을 수 있으므로 보통 넣는 것으로 알고 있습니다. 스누티티의 AppState에도 넣을 예정입니다. (추후 필요가 없다면 삭제하면 그만이니까요)

2022-04-24 06:19 UTC, shp7724 commented
일단 present 방식으로 바꿔둔 상태입니다.

2022-04-27 12:54 UTC, peng-u-0807 commented
@shp7724 혹시 pod 버전은 왜 올리신건가요?

2022-04-27 19:25 UTC, shp7724 commented
@peng-u-0807 ..? 기존 SNUTT 프로젝트 빌드가 안되길래 올린거긴 합니다만 그 커밋이 왜 이 브랜치에 올라가있는지는 모르겠네요. 
일단 revert 했습니다.

2022-04-30 06:12 UTC, JSKeum approved these changes
좋아요

2022-04-30 06:38 UTC, JSKeum commented
HIG에서는 모달 띄울 때 말고는 탭바 가리지 말라고 하네요. Global control이기 때문에
https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/

2022-04-30 07:00 UTC, peng-u-0807 approved these changes
좋습니다

2022-04-30 07:29 UTC, merged