Release 2.1.1
wafflestudio/SNUTT-iOS pull request #66
Opened 2022-04-30 02:30 UTC by JSKeum

강의평 출시 버전 : 2.1.0

2.1.1은 기존의 이슈들 몇개 해결한 버전
1. 0~23시 시간 설정 이슈
2. 위젯에 테마 반영이 안되는 이슈
3. 검색 뷰에서 강의 이름 길 때 짤리는 이슈

2022-04-30 02:40 UTC, shp7724 reviewed
#65 관련해서, *시간표 시작 시각*은  "자동 맞춤"이 되어있더라도 수동으로 설정한 시작 시각에 영향을 받는 것 같습니다. 스크린샷 댓글로 달았으니 확인 부탁드려요.

2022-04-30 05:54 UTC, JSKeum commented
#67 로 PR 올렸씁니다

2022-05-06 14:42 UTC, shp7724 approved these changes

2022-05-23 15:17 UTC, shp7724 commented
#65 관련 버그 재현 영상입니다.

https://user-images.githubusercontent.com/33917774/169851974-80c894d9-1156-4256-95fc-16fc4d4a0bb6.mov

2022-06-28 16:00 UTC, peng-u-0807 requested changes
0~23시 시간 설정 이슈 제외 부탁드립니다

2022-07-08 16:12 UTC, closed without merging