SNUTT AppState 추가 [SNUTT-413]
wafflestudio/SNUTT-iOS pull request #68
Opened 2022-04-30 06:56 UTC by peng-u-0807

## 수정사항
- AppState가 추가되었습니다. 현재로서는 `@Published var`을 이용하여 앱의 상태에 변경사항이 있을 경우, 관련된 view를 모두 업데이트하는 방식을 택하고 있습니다. 아래 간단한 설명 첨부합니다.

- `currentUser`: 현재 유저의 정보, 토큰 등
- `currentTimetable`: 현재 선택된 시간표
- `setting`: 기존 SNUTT의 STDefaults에 해당하는 정보
- `system`: 시스템 상태(showActivityIndicator: 로딩 중, state: 성공/실패(네트워크 등))
- `selectedTab`: 현재 선택된 탭

우선 기본적으로 필요할 것 같은 정보를 넣어둔 상태입니다. 필요에 따라 새로운 변수를 적절히 수정하거나 지우면서 사용하시면 될 것 같습니다.

## 사용 예시
- AppState는 EnvironmentObject로 사용되어, 앱 전반에서 하나의 변수를 공유하는 방식입니다. SNUTTApp에서 AppState 객체 생성 후 상위 View에 `.environmentObject()`로 전달하면 AppState를 사용하고자 하는 view에서(사실상 모든 view에서) `@EnvironmentObject var appState: AppState` 선언을 통해 AppState의 값을 읽거나 변경할 수 있습니다. 
- 홈 화면에서 강의를 선택해서 detailView로 넘어갈 때 AppState의 showActivityIndicator가 true <-> false 로 번갈아 전환되고, 홈 화면에서는 현재 showActivityIndicator의 값을 콘솔에서 출력하도록 되어 있습니다. 값이 제대로 변경되고 있는 점을 확인하실 수 있습니다.

2022-04-30 10:07 UTC, shp7724 requested changes

2022-04-30 10:07 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
![image](https://user-images.githubusercontent.com/33917774/166100966-6f3ce7c7-0843-4d03-909c-a3e96a495a57.png)


저희가 논의한 아키텍쳐대로라면 `AppState`는 View가 아니라 ViewModel에서 직접 참조해줘야 할 것 같습니다.
그런데 조금 찾아보니 ViewModel에는 `environmentObject(_:)` 방식으로 DI를 할 수는 없는 것 같더라구요.
그래서 [이 사람](https://nalexn.github.io/clean-architecture-swiftui/)은 어떻게 하고 있나 보니 `DIContainer`를 만들어서 ViewModel에서 `AppState`에 접근하고 있는 것으로 보입니다.
이 방식도 나쁘진 않지만.. 저는 약간 hacky하다는 생각이 들어서 마음에 들지는 않네요. 이 부분 아키텍쳐를 어떻게 수정하면 좋을지 여기서 논의해보면 좋을 것 같습니다. 

저는 일단 AppState와 ViewModel을 가리키는 멤버 변수를 View 안에 두고, ViewModel을 init할 때 인자로 appState를 전달해주는 방식이 그나마 깔끔한 방식이라고 생각합니다. (물론 이때 View는 Stateful View를 의미합니다. Stateless View라면 상위 View에서 init된 ViewModel을 전달받을테니 appState를 직접 참조할 필요가 없겠죠? 그런 의미에서 Stateless View인 `TimetableList`는 `appState`가 필요하지 않을 것 같습니다.)

@JSKeum님은 어떻게 생각하시나요?

2022-05-01 08:20 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +                    LectureDetails().environmentObject(self.appState)
@shp7724 앗 그러게요 왜 environmentObject가 저기에도 주입되어있죠...? SNUTTApp에서 한번 주입되어 있어서 그 아래로는 필요가 없는데, 이전에 적어두고 미처 발견을 못한 것 같습니다. 👀

2022-05-01 08:21 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/SNUTTApp.swift
>              }
그렇네요 지금은 Scene이 임시로 하나 뿐이지만 여러개가 될 예정이므로 NavigationView에 넘기는 것이 맞을 것 같습니다. 수정할게요

2022-05-01 14:58 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +                    LectureDetails().environmentObject(self.appState)
> 위에서 말씀드린것과 관련해서, NavigationView에다가 environmentObject를 주입해주어야(그 하위 뷰가 아니라요) NavigationLink에 속한 view에 environmentObject가 잘 전달될 것 같습니다.

이전 버전에서는 NavigationView에다가 environmentObject를 주입해주지 않았었기 때문에 여기서 주입해줬어야 했을거에요. 안그럼 빌드가 안되더라구요.

2022-05-02 09:45 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
View 안에 AppState와 ViewModel을 가리키는 멤버 변수를 두겠다는 것은 2개의 변수를 두겠다는 말씀이 맞으실까요? 그렇게 되면 여전히 view에서 AppState를 직접적으로 들고있게 되기 때문에 실질적으로는 큰 효용이 없을 것 같습니다. ViewModel용 프로토콜을 하나 작성한 뒤 변수로 appState를 들고 있도록 하고, 모든 ViewModel이 이 프로토콜을 따르도록 + AppState는 `SNUTTApp.swift`에서 한번만 선언되고 그 하위 뷰로 계속 전달해주는 방식 쪽으로 구체화하는 그림이 좀 더 목적에 부합할 것 같다는 생각입니다.

2022-05-02 10:57 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
구체적으로 어떤 방식을 생각중이신가요?
하위 뷰모델로 `appState`를 계속 전달해주려면 결국 뷰에 `appState` 변수가 있어야 하는 것 아닌가요?

```swift
struct SampleView: View {
    
    let viewModel: TimetableViewModel
    
    init(appState: AppState) {
        viewModel = TimetableViewModel(appState: appState)
    }
    
    var body: some View {
        ...
    }
}
```

아니면 혹시 이런 방식일까요?

2022-05-02 13:35 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
@shp7724 아 저는 view가 아니라 viewModel쪽에 init한다고 생각하여 대략 아래와 같은 구조를 생각 중이었습니다.
```Swift
@main
struct SNUTTApp: App {
    @StateObject var appState = AppState()
    var body: some Scene {
        WindowGroup {
            NavigationView {
                MyTimetableListScene(viewModel: TimetableViewModel(appState: appState))
            }
        }
    }
}
```
```Swift
protocol SNUTTViewModel {
    var appState: AppState { get set }
}

class TimetableViewModel: ObservableObject, SNUTTViewModel {
    @Published var appState: AppState

    init(appState: AppState) {
        self.appState = appState
    }
}
```
```Swift
struct MyTimetableListScene: View {
    @ObservedObject var viewModel: TimetableViewModel
    
    var body: some View {
        TimetableList(viewModel: viewModel, lectures: ///)
    }
}
```

2022-05-02 13:57 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
그렇군요. 올려주신 코드만 보면 제가 처음에 제안했던 방식과 꽤 유사해보이는데, 
그럼 View Hierarchy가 매우 깊고 복잡하다고 가정한다면 하위 뷰에 `appState`를 어떻게 전달해주나요?

(예를 들면, `SNUTTApp` -> `AView` -> `BView` + `BViewModel` -> `CView` + `CViewModel` -> `DView` + `DViewModel`와 같이 구성되어 있는 상황에서, `BView(Model)`과 `CView(Model)`은 `appState`가 필요하지 않지만 `DView(Model)`은 `appState`가 필요한 경우)

2022-05-05 04:43 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
@peng-u-0807 바쁘신가용 👀

2022-05-06 17:48 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
@shp7724 최근 며칠 다른 일이 많아서 확인을 못했네요 이번 주말내로 답변 드릴게요

2022-05-08 15:34 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
@shp7724 
굳이 구현하자면 중간에 있는 View(Model)이 하위 ViewModel을 미리 받아서 아래로 전해주는 방법으로 구현할 수 있긴 하지만, 그리 좋은 방식은 아니므로 위의 방법은 deep한 hierarchy를 가지는 상태에서 AppState를 전달하는데 꽤나 복잡하다는 점은 사실입니다. 생각을 좀 해봤는데, 결국엔 중간 다리가 필요할 것 같다는 결론입니다. 크게 AppState -> 연결 -> 최상위 ViewModel -> 하위 ViewModel의 흐름으로 

```Swift
@main
struct SNUTTApp: App {
    @StateObject var appState = AppState()
    
    var body: some Scene {
        let _ = SNUTTContainer.shared.setAppState(appState: appState)
        
        WindowGroup {
            NavigationView {
                SomethingView(viewModel: SomethingViewModel())
            }
        }
    }
}
```
```Swift
// AppState와 최상위 VIewModel 연결
class SNUTTContainer {
    
    @Published fileprivate var appState: AppState?
    static let shared = SNUTTContainer()
    private init() { }
    
    func setAppState(appState: AppState) {
        self.appState = appState
    }
}
```
```Swift
// 최상위 ViewModel
class SNUTTViewModel: ObservableObject {
    @Published var appState: AppState
    
    init() {
        appState = SNUTTContainer.shared.appState!
    }
}
```
이름은 일단 가칭으로 `Container`로 했습니다만, 이렇게 되면 이번에는 AppState의 극히 일부가 변경되었을 때 모든 ViewModel이 새로 init되는 문제가 있습니다. 그래서 이를 해결하기 위해 추가적인 작업이 더 필요하겠지만 중간 다리가 최선의 선택일 것 같다는 생각입니다. 추가적인 작업을 하다보면 결국 [예시](https://github.com/nalexn/clean-architecture-swiftui)와 어느정도 비슷해질 것 같긴 하네요. 혹시 신홍님께서는 다른 생각이나 해결책이 있으실까요?

2022-05-09 16:17 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
올려주신 코드에 대해 몇 가지 궁금한 점이 있는데요,

1. SNUTTContainer의 appState에 `@Published`가 붙어있는 이유는 무엇인가요? `SNUTTContainer`는 ObservableObject가 아니므로 appState를 외부에서 구독하고 있는게 아닌 한 `@Published`를 붙이는 의미가 없지 않나 해서요.
2. AppState의 일부가 변경되었을 때 모든 ViewModel이 새로 init되는 이유가 `AppState 변경 -> SNUTTApp.body re-eval -> 모든 하위 뷰 reinit & re-eval -> 모든 ViewModel도 reinit` 이거 말씀하신 것 맞을까요?

`DIContainer`도 말씀하신 비효율성을 해결하기 위해 [RxSwift스러운](https://github.com/nalexn/clean-architecture-swiftui/blob/9f2a98a7146f2e28fe44c53d3b9f20620f203baa/CountriesSwiftUI/UI/Screens/CountriesList/CountriesListViewModel.swift#L50) 방식을 채택하고 있는 것 같네요.

---

> View 안에 AppState와 ViewModel을 가리키는 멤버 변수를 두겠다는 것은 2개의 변수를 두겠다는 말씀이 맞으실까요? 그렇게 되면 여전히 view에서 AppState를 직접적으로 들고있게 되기 때문에 실질적으로는 큰 효용이 없을 것 같습니다.

그런데 저는 말씀하신 문제를 해결하기 위해 이렇게 멀고 복잡한 길로 돌아가는 것이 리팩토링의 취지에 맞는지 고민이 됩니다. 약간 주객이 전도되는 듯한 느낌이랄까요..? SwiftUI로 리팩토링하는 이유가 가독성이 좋고 유지보수하기 쉬운 코드를 작성하기 위해서라고 한다면, 저희가 목표로 했던 아키텍쳐에서 어느정도 타협을 할 수도 있지 않을까요?

그래서 저는 여전히 @EnvironmentObject를 통해 AppState를 전달하는 방식이 가장 직관적이고 효율적인 방법이라고 생각합니다. View가 AppState를 참조할 수 없다는 제한만 푼다면, 별도의 Container나 pub-sub 패턴을 구현하지 않아도 되고, 뷰 update도 비교적 효율적으로 진행될 것이기 때문에요.

2022-05-11 14:44 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
> 그렇군요. 올려주신 코드만 보면 제가 처음에 제안했던 방식과 꽤 유사해보이는데, 그럼 View Hierarchy가 매우 깊고 복잡하다고 가정한다면 하위 뷰에 `appState`를 어떻게 전달해주나요?
> 
> (예를 들면, `SNUTTApp` -> `AView` -> `BView` + `BViewModel` -> `CView` + `CViewModel` -> `DView` + `DViewModel`와 같이 구성되어 있는 상황에서, `BView(Model)`과 `CView(Model)`은 `appState`가 필요하지 않지만 `DView(Model)`은 `appState`가 필요한 경우)

(위) 각 scene마다 하나의 stateful view + 여러 stateless view들로 구성되어 있다면, stateful view에만 viewModel이 들어갈테니 이런 경우는 거의 안 나오지 않을까요?? 그래서 (아래) 유림님이 제시한 구조 괜찮아 보입니다. 메인 뷰를 초기화할 때 한번 AppState를 주입하는 게 깔끔해 보이네요. 근데 불가피하게 하위 뷰에서 AppState를 가져다 써야 하는 경우에는 AppState -> ViewModel -> View 구조가 깨지는 경우가 발생할 수도 있겠네요. 

> @shp7724 아 저는 view가 아니라 viewModel쪽에 init한다고 생각하여 대략 아래와 같은 구조를 생각 중이었습니다.
> 
> ```swift
> @main
> struct SNUTTApp: App {
>     @StateObject var appState = AppState()
>     var body: some Scene {
>         WindowGroup {
>             NavigationView {
>                 MyTimetableListScene(viewModel: TimetableViewModel(appState: appState))
>             }
>         }
>     }
> }
> ```
> 
> ```swift
> protocol SNUTTViewModel {
>     var appState: AppState { get set }
> }
> 
> class TimetableViewModel: ObservableObject, SNUTTViewModel {
>     @Published var appState: AppState
> 
>     init(appState: AppState) {
>         self.appState = appState
>     }
> }
> ```
> 
> ```swift
> struct MyTimetableListScene: View {
>     @ObservedObject var viewModel: TimetableViewModel
>     
>     var body: some View {
>         ///
>     }
> }
> ```

2022-05-11 14:44 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
@shp7724 님이 생각하신 구조는 다음과 같은 방식이 맞나요?
```swift
struct StatefulView: View {
  @EnvironmentObject var appState: AppState
  @ObservedObject var viewModel = YourViewModel(appState: appState)
  
  var body: some View {}
}
```

2022-05-11 15:13 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
> 저는 일단 AppState와 ViewModel을 가리키는 멤버 변수를 View 안에 두고, ViewModel을 init할 때 인자로 appState를 전달해주는 방식이 그나마 깔끔한 방식이라고 생각합니다. 

@shp7724 요건 구체적으로 어떤 형태가 될까요??

2022-05-11 16:16 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
> 각 scene마다 하나의 stateful view + 여러 stateless view들로 구성되어 있다면, stateful view에만 viewModel이 들어갈테니 이런 경우는 거의 안 나오지 않을까요?

확실한 건 좀 더 구현해봐야 알 것 같긴 한데, 일단 저는 그런 경우가 종종 발생할 것이라고 생각했습니다.

> 근데 불가피하게 하위 뷰에서 AppState를 가져다 써야 하는 경우에는 AppState -> ViewModel -> View 구조가 깨지는 경우가 발생할 수도 있겠네요.

만약 이런 케이스가 생긴다면, 유림님이 말씀하신대로 AppState를 하위 뷰에 전달하는 방식이 조금 깔끔하지 않게 될 것 같긴 해요.

> @shp7724 님이 생각하신 구조는 다음과 같은 방식이 맞나요?

네 맞습니다. `@EnvironmentObject`가 View 안에 있는 것은 당초 논의했던 아키텍쳐와 다르긴 합니다만, `@EnvironmentObject`의 강력한 기능을 사용하는게 코드를 깔끔하게 유지하는 데에 유리하다고 생각했습니다.

2022-05-11 16:46 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
> @shp7724 요건 구체적으로 어떤 형태가 될까요??

대략 아래와 같은 형태를 생각했습니다.

```swift
struct StatefulView: View {
  @EnvironmentObject var appState: AppState
  @ObservedObject var viewModel = ObservableViewModel()
  
  var body: some View {
        StatelessChildView1()
    }
}

struct StatelessChildView1: View {
  // 뷰를 그리는 데에 필요한 로직이 포함된 뷰모델
  var viewModel = NonObservableViewModel1()
 
  var body: some View {
    StatelessChildView2()
}
}

struct StatelessChildView2: View {
  var viewModel = NonObservableViewModel2()
 
  var body: some View {
    StatefulChildView3()
}
}

struct StatefulChildView3: View {
  @EnvironmentObject var appState: AppState
  
  var viewModel = NonObservableViewModel3()
 
  var body: some View {
    Button {
        Text(appState.someText)
    } action: {
        viewModel.changeText()
    }
  }
}
```

```swift
class NonObservableViewModel3 {
    
    func changeText() {
        SNUTTService.requestChangeText()
    }
    
    ...
}
```

```swift
struct SNUTTService {

    static func requestChangeText() {
        doNetworkRequest { response in
            // this change will be propagated to StatefulChildView3
            STContainer.shared.appState.someText = response.text
        }
    }
    
    ...
}
```

2022-05-12 14:12 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
적어주신 경우에는 하위 view에서 AppState, viewModel을 불러오는 것보다는 필요한 state들을 모두 StatefulView에서 불러온 후 아래로 넘겨주는 것이(React의 Props처럼) 자연스러워 보입니다. statefulView가 data container의 역할을 하는 겁니다.

```swift
struct StatefulView: View {
    @ObservedObject var viewModel: TimetableViewModel
    
    var body: some View {
        StatelessChildView1(timetable: viewModel.timetable, changeTimetable: viewModel.change)
    }
}

struct StatelessChildView1: View, ChangeTimetableProtocol {
  var timetable: Timetable
  
  var body: some View {
        StatelessChildView2(changeTimetable: changeTimetable)
    }
}

struct StatelessChildView2: View, ChangeTimetableProtocol {
  var timetable: Timetable
  
  var body: some View {
        Button(action: changeTimetable)
    }
}

protocol ChangeTimetableProtocol {
   var changeTimetable: () -> ()
}

extension ChangeTimetableProtocol {
 var changeTimetable = {}
}
```

그리고 합성(composition)을 이용하는 것도 좋은 방법입니다.

2022-05-13 08:04 UTC, JSKeum commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
model과 무관한 로직은 viewModel이 아닌 view에 넣으면 되지 않을까요? 구체적인 케이스가 지금은 잘 떠오르지 않네요. 지금은 ViewModel에 들어있는 것들은 Container에서 Stateless로 넘겨주는게 자연스러워 보이기는 합니다.

`(아래) 유림님이 제시한 구조`를 따라가면 좋을 것 같습니다. 만약 개발하다가 신홍님이 걱정하신 부분이 많이 드러난다 싶으면 수술을 해야지요

2022-05-13 18:01 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/TimetableList.swift
> +    var lectures: [Lecture]
> 올려주신 코드에 대해 몇 가지 궁금한 점이 있는데요,
> 
> 1. SNUTTContainer의 appState에 `@Published`가 붙어있는 이유는 무엇인가요? `SNUTTContainer`는 ObservableObject가 아니므로 appState를 외부에서 구독하고 있는게 아닌 한 `@Published`를 붙이는 의미가 없지 않나 해서요.
> 2. AppState의 일부가 변경되었을 때 모든 ViewModel이 새로 init되는 이유가 `AppState 변경 -> SNUTTApp.body re-eval -> 모든 하위 뷰 reinit & re-eval -> 모든 ViewModel도 reinit` 이거 말씀하신 것 맞을까요?
> 
> `DIContainer`도 말씀하신 비효율성을 해결하기 위해 [RxSwift스러운](https://github.com/nalexn/clean-architecture-swiftui/blob/9f2a98a7146f2e28fe44c53d3b9f20620f203baa/CountriesSwiftUI/UI/Screens/CountriesList/CountriesListViewModel.swift#L50) 방식을 채택하고 있는 것 같네요.
> 
> > View 안에 AppState와 ViewModel을 가리키는 멤버 변수를 두겠다는 것은 2개의 변수를 두겠다는 말씀이 맞으실까요? 그렇게 되면 여전히 view에서 AppState를 직접적으로 들고있게 되기 때문에 실질적으로는 큰 효용이 없을 것 같습니다.
> 
> 그런데 저는 말씀하신 문제를 해결하기 위해 이렇게 멀고 복잡한 길로 돌아가는 것이 리팩토링의 취지에 맞는지 고민이 됩니다. 약간 주객이 전도되는 듯한 느낌이랄까요..? SwiftUI로 리팩토링하는 이유가 가독성이 좋고 유지보수하기 쉬운 코드를 작성하기 위해서라고 한다면, 저희가 목표로 했던 아키텍쳐에서 어느정도 타협을 할 수도 있지 않을까요?
> 
> 그래서 저는 여전히 @EnvironmentObject를 통해 AppState를 전달하는 방식이 가장 직관적이고 효율적인 방법이라고 생각합니다. View가 AppState를 참조할 수 없다는 제한만 푼다면, 별도의 Container나 pub-sub 패턴을 구현하지 않아도 되고, 뷰 update도 비교적 효율적으로 진행될 것이기 때문에요.

@shp7724 
2번에 대해서는 SNUTTApp에서 변화가 감지된다기 보다는 SNUTTViewModel이 ObservableObject이고, 그 뷰모델을 ObservedObject로 들고 있기 때문에 AppState가 변경되면 그 appState를 들고 있는 뷰모델의 멤버 변수가 변경된 것이므로 뷰모델이 값을 새로 가져오며 View를 새롭게 그린다에 가까울 것 같네요.

2022-05-28 10:31 UTC, shp7724 commented on SNUTT-2022/SNUTT/ViewModels/SNUTTViewModel.swift
> +}
@JSKeum @peng-u-0807 좀 더 실험을 해보니 위 말은 반쯤 맞고 반쯤 틀린 말인 것 같아서 정정하겠습니다. `@StateObject`가 이벤트를 받아서 `SNUTTApp`의 body를 recompute하고, 그 과정에서 TimetableViewModel이 새롭게 초기화되면서 해당 viewModel을 전달받는 뷰들이 recompute되는 것 같습니다.

대신 property가 변하지 않은 View는 상위 뷰가 리렌더링이 되어도 렌더링하지 않도록 내부적으로 최적화를 해주는 것 같습니다.
다시 말해 `SNUTTApp`이 recompute되면서 새롭게 초기화되는 viewModel들의 영향을 받는 뷰만 새롭게 recompute된다고 생각하면 될 것 같아요. 이게 성능에 영향을 미칠지는 구현 방식에 따라 조금씩 달라질 것 같습니다.

2022-05-28 10:35 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/SNUTTApp.swift
> +
그리고 이런 imperative(명령형) 코드가 declarative syntax에 섞여들어가는게 (코드 퀄리티의 측면에서) 개인적으로 좀 불편한 느낌도 있는 것 같습니다.

2022-06-11 06:09 UTC, shp7724 approved these changes
conflict 해소되면 머지해주세용

2022-06-11 07:25 UTC, merged