`BaseViewModel` 생성, 강의 디테일 화면 구현
wafflestudio/SNUTT-iOS pull request #88
Opened 2022-07-12 15:13 UTC by shp7724

- 강의 디테일 뷰를 간단하게 구현했습니다 (편집, 테마 변경은 TODO)
- 깊숙한 곳에 들어있는 StatelessView에서 `Scene`으로 navigate할 때, `container`를 어떻게 전달해줄지 [이전에 얘기하다 만 적](https://github.com/wafflestudio/SNUTT-iOS/pull/78#discussion_r912293762)이 있어서, 여기서 다시 논의해보면 좋을 것 같아요. 일단은 제가 얘기했던 방식으로 구현해 둔 상태입니다.

https://user-images.githubusercontent.com/33917774/178524165-84a958b0-b83a-499d-8f7d-804bfe12b6fc.mov

2022-07-14 19:03 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    .foregroundColor(preventEditing ? Color(uiColor: .label.withAlphaComponent(0.6)) : Color(uiColor: .label))
@shp7724 placeholder는 아래와 같이 구현할 수 있습니다.
```Swift
ZStack(alignment: .leading) {
    if text.isEmpty {
        Text("(없음)")
    } else {
        TextEditor(text: $text)
            .disabled(!isEditing || preventEditing)
            .opacity(text.isEmpty ? 0 : 1)
        Text(text).opacity(0).padding([.vertical, .trailing], 10)
    }
}
```
다만 SwiftUI의 `TextEditor`는 Inset을 더이상 수정할 수가 없기 때문에 UI를 통일하려면 결국 커스텀 뷰를 이용해야되지 않을까요?

2022-07-15 02:26 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    .foregroundColor(preventEditing ? Color(uiColor: .label.withAlphaComponent(0.6)) : Color(uiColor: .label))
@peng-u-0807 커스텀 뷰라는게 어떤걸 말씀하시는건가요? UIViewRepresentable을 사용하지 않고 정렬 안맞는 문제를 해결할 수 있을까요?

2022-07-16 13:44 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    .foregroundColor(preventEditing ? Color(uiColor: .label.withAlphaComponent(0.6)) : Color(uiColor: .label))
일단 Inset 5로 하드코딩해서 진행해볼게요.

2022-07-17 16:36 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +        .font(.system(size: 16, weight: .regular))
@peng-u-0807 @JSKeum 제가 이거때문에 7시간정도 썼는데요... 결론적으로 UIKit을 사용하지 않으면서도 **버그 없는** dynamic height, multiline text editor를 구현하는 건 불가능한 것 같습니다. 구글링하면 나오는 pure SwiftUI 솔루션들도 깔끔한 해결책은 아니더라고요. 예를 들면,

- `TextEditor` 위에 똑같은 텍스트가 담긴 `TextField`를 올리고, 그 `TextField`의 높이에 따라 `TextEditor`의 높이도 바뀌도록 구현 -> 엔터를 마구 누르면 텍스트가 미세하게 떨리는 버그 발생
- `TextEditor`의 inset을 조정하기 위해, `.padding(EdgeInset(top: -2, left: -5, bottom: -2, right: -5))`와 같이 하드코딩된 값으로 padding 제거 -> 어쨌든 하드코딩이니 좋은 방법은 아니라고 생각합니다.
- 이 밖에도 버그 하나 고치면 다른 버그가 생기고...의 반복이더라고요.

대신 (직접 구현한) `UITextEditor`를 사용하면 다음과 같은 장점이 있습니다.
- TextEditor Inset을 하드코딩 없이 손쉽게 제거 가능
- `TextField`와 동일한 문법으로 placeholder 사용 가능 (ZStack 안써도 됨)
- 커서가 키보드에 항상 가리지 않도록 만들 수 있음 (오리지널 버전에도 이 문제는 있더라고요)
- 버그가 없다

2022-07-29 18:50 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +        .font(.system(size: 16, weight: .regular))
@shp7724 말씀하신대로 `UIViewRepresentable`을 통해 아직 SwiftUI가 완전히 커버하지 못한 UIKit의 UIView를 구현하는 것도 좋은 방법이라고 생각합니다. 그런데 SingleLine, Multiline 상관 없이 모두 TextEditor로 설정한 뒤 SingleLine에 한해 `.lineLimit`을 걸어주고 좌측 라벨(학과, 학점, 비고 등)의 `leading에 padding 추가 + trailing의 padding 제거`를 하면 pure SwiftUI로 필요한 모든 기능(언급해주신 dynamic height, multiline, 커서가 키보드에 가리지 않음)을 구현할 수 있지 않나요?

2022-07-30 00:38 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +        .font(.system(size: 16, weight: .regular))
@peng-u-0807 이유는 모르겠지만 제가 실험해봤을 땐 `lineLimit` modifier가 TextEditor에는 적용되지 않는 것 같았습니다. iOS16부터는 TextField를 multiline으로 만들 수 있다고 하던데, 베타라 그런지 `텍스트가 미세하게 떨리는 버그`는 그대로더라고요.

2022-07-31 07:52 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +        .font(.system(size: 16, weight: .regular))
@shp7724 [찾아보니](https://stackoverflow.com/questions/68171072/line-limit-in-texteditor-swiftui-not-working) `lineLimit` modifier은 `Text`에만 적용 가능한 것으로 보이는데 왜 `TextEditor`에서 호출할 수 있도록 열어놨는지는 모르겠네요. `UIViewRepresentable`을 이용하는 것이 가장 좋을 것 같습니다.

2022-07-31 07:53 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/UITextEditor.swift
> +        private func ensureCursorVisible(textView: UITextView) {
편집할 때 입력 과정에서는 키보드가 커서를 가리지 않지만, TextView를 처음으로 탭하는 `startEditing` 단계에서는 커서가 여전히 가려지는 문제가 있는 것 같습니다.

2022-07-31 14:54 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/UITextEditor.swift
> +        private func ensureCursorVisible(textView: UITextView) {
@peng-u-0807 네, 해당 문제 인지는 하고 있는데 키보드가 열리기 전에 ensureCursorVisible 함수가 호출되기 때문인 걸로 기억하고 있어요. 이걸 해결하려면 키보드가 열린 직후에 ensureCursorVisible 함수가 호출되도록 만들어야 하는데, `NotificationCenter`를 사용하는 것 외에 더 깔끔한 방법이 떠오르지 않아서 보류하고 있었습니다. 고치는게 좋을까요?

2022-07-31 17:30 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    Button {
https://user-images.githubusercontent.com/70614553/182038307-7027fdc4-81bb-4546-aaa0-cdc89c6fabe8.mp4

편집 도중 취소 버튼을 눌렀을 때 서버에는 저장결과가 반영되지 않도록 잘 구현되었지만, 현재 뷰에서 보여주는 `UITextEditor`의 text값이 변하지 않는 문제가 있습니다.

2022-07-31 17:33 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    Button {
https://user-images.githubusercontent.com/70614553/182038307-7027fdc4-81bb-4546-aaa0-cdc89c6fabe8.mp4

편집 도중 취소 버튼을 눌렀을 때 서버에는 저장결과가 반영되지 않도록 잘 구현되었지만, 현재 뷰에서 보여주는 `UITextEditor`의 text값이 변하지 않는 문제가 있습니다.

2022-07-31 17:35 UTC, peng-u-0807 commented on SNUTT-2022/SNUTT/Views/Components/UITextEditor.swift
> +        private func ensureCursorVisible(textView: UITextView) {
@shp7724 아직까진 SwiftUI로 keyboard 높이를 받아오는 방법이 없는 것으로 보입니다. 이것저것 예제를 찾아봤지만 모두 결국엔 `NotificationCenter`를 이용하네요

2022-08-01 01:28 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/UITextEditor.swift
> +        private func ensureCursorVisible(textView: UITextView) {
@peng-u-0807 네 그런 것 같더라고요. NotificationCenter 사용하는 것 동의하시면 한번 수정해볼게요. @JSKeum

2022-08-01 07:29 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    Button {
@peng-u-0807 해당 버그 수정했습니다. 또 문제 생기면 알려주세요.

2022-08-01 07:31 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
> +                    Button {
아 커밋 로그 꼬일 것 같아서 #89 브랜치에서 수정했습니다.

2022-08-20 03:36 UTC, JSKeum requested changes

2022-08-20 03:36 UTC, JSKeum commented on SNUTT-2022/SNUTTTests/LectureRepositoryTests.swift
> +    }
api key와 access token은 git에 넣지 않는게 좋을 것 같아요

2022-08-20 03:37 UTC, JSKeum commented
changes에 PopupView랑 Sheet도 있던데, 모두 이 PR에서 변경하려고 의도한 것이 맞나요?

2022-08-20 03:49 UTC, shp7724 commented on SNUTT-2022/SNUTTTests/LectureRepositoryTests.swift
> +    }
헉 이게 언제 들어갔지..
지우겠습니다

2022-08-20 06:45 UTC, JSKeum approved these changes
고생하셨어요~

2022-08-20 08:49 UTC, shp7724 commented on SNUTT-2022/SNUTT/Views/Components/UITextEditor.swift
> +        private func ensureCursorVisible(textView: UITextView) {
일단 백로그로 남기고 다음에 수정하는것으로 하겠습니다.

2022-08-20 09:07 UTC, merged