Autofit 구현
wafflestudio/SNUTT-iOS pull request #94
Opened 2022-08-05 04:03 UTC by shp7724

- 시간표 autofit 을 구현했습니다.

https://user-images.githubusercontent.com/33917774/182999149-0a86fd58-aaf6-4e8f-92fe-801e425b8f8c.mov

2022-08-06 04:55 UTC, peng-u-0807 reviewed
https://user-images.githubusercontent.com/70614553/183234517-0f85af1f-8557-46cb-9de1-8038f9fa6c49.mp4

강의 검색 탭에서 강의를 추가하고 시간표 탭으로 다시 돌아오면 튕기는 듯한 애니메이션이 있는데 수정할 수 있는 부분이라면 삭제하는 쪽이 좋을 것 같습니다

2022-08-06 05:47 UTC, shp7724 commented
>

2022-08-06 05:49 UTC, shp7724 commented
@peng-u-0807 네 일단 해당 애니메이션은 삭제했습니다. 그런데 기존 로직상으로는 강의 추가한 즉시 애니메이션이 시작되어야 하는데(=유저에게 보이지 않아야하는데) 왜 tab을 전환한 이후에 시작되는건지 이해가 잘 안되네요..

2022-08-24 17:35 UTC, peng-u-0807 requested changes
https://user-images.githubusercontent.com/70614553/186485822-55177d5b-4878-4f77-92e8-9132a2b69f57.MP4

`autofit = true`로 설정되어 있더라도 기본은 9시~19시까지 시간표가 보여야 하는데 무조건 end to end를 맞추다보니 영상 같은 케이스가 발생합니다

2022-08-24 18:53 UTC, peng-u-0807 requested changes
```

2022-08-24 19:17 UTC, peng-u-0807 approved these changes
수고하셨습니다~👍🏻 위의 `request changes`는 Git GUI 이슈로 실수로 남긴 것이니 무시하셔도 됩니다

2022-08-24 19:40 UTC, merged