시간표 이름변경/테마 변경/삭제 구현
wafflestudio/SNUTT-iOS pull request #96
Opened 2022-08-06 12:11 UTC by shp7724

- 시간표 관련 작업들을 구현했습니다.
- 시간표 이름 변경의 경우 iOS 15 이하에서 TextField가 포함된 Alert를 생성하는 것이 까다로워서 Sheet로 처리했습니다.

https://user-images.githubusercontent.com/33917774/183248372-5eccb28e-ad9f-40a8-aefd-d4c495b98935.mov

2022-08-20 03:47 UTC, JSKeum requested changes

2022-08-20 03:47 UTC, JSKeum commented on SNUTT-2022/SNUTT/Services/AppService.swift
> +struct AppService: AppServiceProtocol {
이름을 AppService로 하기 보다는 좀더 이해하기 쉽게, GlobalUiService 같은 걸로 바꾸면 어떨까요?

2022-08-20 03:47 UTC, JSKeum commented on SNUTT-2022/SNUTT/Services/TimetableService.swift
> +                appState.timetable.metadataList = timetables
UI 로직이 Service layer에 있는게 맞을까요? UI 로직은 ViewModel에 넣는게 좋을 것 같은데, 그렇게 구현할 떄 문제가 있을까요?

2022-08-20 09:10 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/TimetableService.swift
> +                appState.timetable.metadataList = timetables
네 `withAnimation`은 가능하다면 빼는게 좋아보입니다. 해당`appState`의 영향을 받는 모든 View를 찾아 `.animation` modifier를 적용해준다면 가능할 것 같아요.

2022-08-20 09:11 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/AppService.swift
> +struct AppService: AppServiceProtocol {
좋아요. 근데 U`i`가 전 좀 어색하게 느껴지는데 `GlobalUIService`는 어떤가요?

2022-08-23 08:29 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/TimetableService.swift
> +                appState.timetable.metadataList = timetables
해당 변경사항은 #101 에서 구현되었습니다.

2022-08-23 08:51 UTC, shp7724 commented on SNUTT-2022/SNUTT/Services/AppService.swift
> +struct AppService: AppServiceProtocol {
해당 변경사항은 #101  에서 구현되었습니다.

2022-08-24 18:59 UTC, peng-u-0807 requested changes
```

2022-08-25 18:12 UTC, peng-u-0807 approved these changes

2022-08-26 01:00 UTC, shp7724 commented
@peng-u-0807 학점 수 동기화 안되는 문제는 다른 브랜치였던건가요? 일단 여기서는 잘 되는 것 같으니 머지하겠습니다!

2022-08-26 01:00 UTC, merged